### ISSUE TITLE
Helap

### ISSUE THREAD

**Issue by barn-advisor** [000yesnt/testgame#3]
I nO kNOw pythuin palse i need run gayme :(

**Comment by 000yesnt** [comment]
cum nigga penis

**Comment by barn-advisor** [comment]
oh no it crashed plaes fix sir
`UH oh crashed
<0XDEADNIGER>
it no workig
python 0.00001`

**Comment by 000yesnt** [comment]
dont forget to pet your cat
also how are you contributor now
